# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1


orbs:
    core: ren/circleci-orbs@dev:first

_defaults: &defaults
    docker:
      # specify the version
      - image: circleci/golang:1.12
    working_directory: ~/sample-go-app

commands:
  patch_version:
    description: Patches the version key of a JSON file with branch name and date
    parameters:
      file:
        description: The file to be patched
        type: string
    steps:
      - run:
          name: Install JQ
          command: |
            if ! [ -x "$(command -v jq)" ]; then
              sudo apt-get install jq
            fi
      - run:
          name: Patching version
          command: |
            branch=$(git branch | grep \* | cut -d ' ' -f2)
            if [ "${branch}" != "stable" ]
            then
              timestamp=$(date +"%Y%m%d")
              tmp=$(mktemp)
              jq --arg suffix "-${branch}.${timestamp}" '.version += $suffix' << parameters.file >> > "$tmp" && mv -f "$tmp" << parameters.file >>
            fi
  deploy:
    description: Deploy
    parameters:
      file:
        description: The file to be patched and deployed
        type: string
    steps:
      - patch_version:
          file: << parameters.file >>
      - core/install_ghr
      - run:
          name: Deploy to Github Releases
          command: |
            ver=$(jq -r '.version' << parameters.file >>)
            echo "v${ver}"
            cat << parameters.file >>
            ghr "v${ver}" << parameters.file >>
  rw_checkout:
    description: "Checkout with Read/Write Privileges"
    steps:
      - run:
          name: Setup Git
          command: |
            export RW_REPO_URL="https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

            if [ -e ${CIRCLE_WORKING_DIRECTORY}/.git ]
            then
              cd ${CIRCLE_WORKING_DIRECTORY}
              git remote set-url origin "${RW_REPO_URL}" || true
              git fetch --force origin "master:remotes/origin/master"
            else
              mkdir -p ${CIRCLE_WORKING_DIRECTORY}
              cd ${CIRCLE_WORKING_DIRECTORY}
              git clone ${RW_REPO_URL} .
            fi
            git fetch --all
  merge:
    description: "Merge from branch into another branch"
    parameters:
      from:
        description: The branch with changes to be merged into another branch
        type: string
      into:
        description: The branch onto which changes will be applied
        type: string
    steps:
      - rw_checkout
      - run:
          name: Merging branch
          command: |
            git reset --hard
            git checkout --track origin/<< parameters.into >>
            git merge origin/<< parameters.from >> -v
            git push

jobs:
  deploy:
    <<: *defaults
    steps:
      - rw_checkout
      - deploy:
          file: config.json
  fake_activity:
    <<: *defaults
    steps:
      - rw_checkout
      - run:
          name: Making a random commit
          command: |
            git reset --hard
            git checkout master
            git config --global user.name "CircleCI"
            git config --global user.email "circleci"
            export NUM="$(( ( RANDOM % 10 )  + 1 ))"
            echo "${NUM}" >> numbers.txt
            git commit -am "CircleCI - Add number (${NUM})"
            git push
  merge_nightly:
    <<: *defaults
    steps:
      - merge:
          from: master
          into: nightly
  merge_beta:
    <<: *defaults
    steps:
      - merge:
          from: nightly
          into: beta
  merge_stable:
    <<: *defaults
    steps:
      - merge:
          from: beta
          into: stable
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
              - ~/sample-go-app/vendor
      - run:
          name: Download dependencies
          command: |
            if [ ! -d ~/sample-go-app/vendor ]; then
                go mod download
                go mod vendor
            else
                echo "Dependencies were restored from cache."
            fi
      - save_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
              - ~/sample-go-app/vendor
      - run:
          name: Building and testing
          command: |
            cd cmd
            go build -v
            ./cmd

workflows:
  version: 2.1
  build:
    jobs:
    - build
  # - deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *" # every night at 02:00
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_nightly:
          filters:
            branches:
              only: master
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *" # on the 1st of every month at 00:00
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_stable:
          filters:
            branches:
              only: master
      - merge_beta:
          filters:
            branches:
              only: master
          # Only run merge_beta after merge_stable is run
          requires:
            - merge_stable
