# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

_defaults: &defaults
    docker:
      # specify the version
      - image: circleci/golang:1.9
    environment:
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.5.0
    working_directory: /go/src/github.com/renproject/sample-go-app

commands:
  rw_checkout:
    description: "Checkout with Read/Write Privileges"
    steps:
      - run:
          name: Setup Git
          command: |
            export RW_REPO_URL="https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

            if [ -e ${CIRCLE_WORKING_DIRECTORY}/.git ]
            then
              cd ${CIRCLE_WORKING_DIRECTORY}
              git remote set-url origin "${RW_REPO_URL}" || true
              git fetch --force origin "master:remotes/origin/master"
            else
              mkdir -p ${CIRCLE_WORKING_DIRECTORY}
              cd ${CIRCLE_WORKING_DIRECTORY}
              git clone ${RW_REPO_URL} .
            fi
            git fetch --all
  merge:
    description: "Merge from branch into another branch"
    parameters:
      from:
        description: The branch with changes to be merged into another branch
        type: string
      into:
        description: The branch onto which changes will be applied
        type: string
    steps:
      - rw_checkout
      - run:
          name: Merging branch
          command: |
            git reset --hard
            git checkout --track origin/<< parameters.into >>
            git merge origin/<< parameters.from >> -v
            git push

jobs:
  merge_nightly:
    <<: *defaults
    steps:
      - merge:
          from: master
          into: nightly
  merge_beta:
    <<: *defaults
    steps:
      - merge:
          from: nightly
          into: beta
  merge_stable:
    <<: *defaults
    steps:
      - merge:
          from: beta
          into: stable
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/renproject/sample-go-app/vendor
      - run:
          name: Download dependencies
          command: |
            if [ ! -d /go/src/github.com/renproject/sample-go-app/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure -v
            else
                echo "Dependencies were restored from cache."
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/renproject/sample-go-app/vendor
      - restore_cache:
          keys:
              - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - run:
          name: Building and testing
          command: |
            mkdir -p $GOCACHE
            cd cmd
            go build -v
            ./cmd
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
              - /tmp/go/cache

workflows:
  version: 2.1
  build:
    jobs:
    - build
  nightly:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"  # every ten minutes
          # cron: "0 0 * * *" # every night at time 00:00
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_nightly
  monthly:
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"  # every fifteen minutes
          # cron: "0 0 1 * *" # every month (on the 1st)
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_beta
      - merge_stable
